import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#3A2B26',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFC400',
  },
  header: {
    backgroundColor: '#3A2B26',
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  headerGreeting: {
    fontSize: 18,
    color: '#FFEFD2',
    fontFamily: 'AtkinsonHyperlegible-Regular',
  },
  headerName: {
    fontSize: 32,
    color: '#FFC400',
    fontFamily: 'Lexend-SemiBold',
  },
  headerTagline: {
    fontSize: 16,
    color: '#FFEFD2',
    fontFamily: 'OpenDyslexic-Regular',
    marginTop: 4,
  },
  headerMascot: {
    width: 88,
    height: 88,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 160,
    gap: 24,
  },
  section: {
    gap: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 22,
    color: '#3A2B26',
    fontFamily: 'Lexend-SemiBold',
  },
  sectionMore: {
    fontSize: 26,
    color: '#3A2B26',
  },
  sectionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 16,
  },
  sectionCard: {
    width: '48%',
    backgroundColor: '#FFEFD2',
    borderRadius: 24,
    padding: 16,
    gap: 8,
    shadowColor: '#3A2B26',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  cardIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#FFC400',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardEmoji: {
    fontSize: 24,
  },
  cardLabel: {
    fontSize: 18,
    color: '#3A2B26',
    fontFamily: 'Lexend-Medium',
  },
  cardHelper: {
    fontSize: 14,
    color: '#6B4F4A',
    fontFamily: 'OpenDyslexic-Regular',
  },
  insightCard: {
    backgroundColor: '#3A2B26',
    borderRadius: 28,
    padding: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  insightTitle: {
    fontSize: 20,
    color: '#FFC400',
    fontFamily: 'Lexend-SemiBold',
    marginBottom: 4,
  },
  insightText: {
    fontSize: 16,
    color: '#FFEFD2',
    fontFamily: 'OpenDyslexic-Regular',
    maxWidth: 220,
  },
  insightAction: {
    fontSize: 32,
    color: '#FF7A28',
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#3A2B26',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingBottom: 20,
    paddingTop: 10,
  },
  bottomNavItem: {
    alignItems: 'center',
    gap: 4,
  },
  bottomNavIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#4F3D39',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomNavEmoji: {
    fontSize: 22,
  },
  bottomNavLabel: {
    color: '#FFEFD2',
    fontSize: 13,
    fontFamily: 'AtkinsonHyperlegible-Regular',
    textAlign: 'center',
  },
  mistakeAnalysisCard: {
    backgroundColor: '#FFEFD2',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#FF7A28',
  },
  mistakeAnalysisTitle: {
    fontSize: 22,
    color: '#3A2B26',
    fontFamily: 'Lexend-SemiBold',
    marginBottom: 8,
  },
  mistakeAnalysisText: {
    fontSize: 16,
    color: '#3A2B26',
    fontFamily: 'OpenDyslexic-Regular',
    marginBottom: 8,
  },
  mistakeAnalysisAction: {
    fontSize: 14,
    color: '#FF7A28',
    fontFamily: 'Lexend-SemiBold',
    textAlign: 'right',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '80%',
    backgroundColor: '#FFEFD2',
    borderRadius: 24,
    padding: 24,
    gap: 16,
  },
  modalTitle: {
    fontSize: 24,
    color: '#3A2B26',
    fontFamily: 'Lexend-SemiBold',
    textAlign: 'center',
  },
  modalText: {
    fontSize: 16,
    color: '#3A2B26',
    fontFamily: 'OpenDyslexic-Regular',
    textAlign: 'center',
  },
  modalButton: {
    backgroundColor: '#FF7A28',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalButtonSecondary: {
    backgroundColor: '#3A2B26',
  },
  modalButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'Lexend-SemiBold',
  },
});
