import { StyleSheet } from "react-native";

const COLORS = {
  background: "#FFC400",
  panel: "#FFEFD2",
  deepBrown: "#3A2B26",
  midBrown: "#4F3D39",
  accent: "#FF7A28",
  cream: "#FFF6E3",
  success: "#34C759",
  warning: "#D04F4F",
  info: "#8B5E3C",
  start: "#2C872F",
  stop: "#C91C1A",
  restart: "#E18F15",
  tts: "#FF7A28",
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.deepBrown,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingBottom: 16,
  },
  header: {
    backgroundColor: COLORS.deepBrown,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: COLORS.midBrown,
    alignItems: "center",
    justifyContent: "center",
  },
  backText: {
    color: COLORS.panel,
    fontSize: 24,
    fontWeight: "bold",
  },
  headerTitle: {
    color: COLORS.panel,
    fontSize: 26,
    fontFamily: "Lexend-SemiBold",
  },
  headerSubtitle: {
    color: COLORS.cream,
    fontSize: 16,
    marginTop: 4,
    fontFamily: "OpenDyslexic-Regular",
  },
  card: {
    flex: 1,
    backgroundColor: COLORS.panel,
    marginHorizontal: 20,
    marginTop: -12,
    borderRadius: 32,
    padding: 20,
    elevation: 6,
  },
  title: {
    fontSize: 24,
    color: COLORS.deepBrown,
    fontFamily: "Lexend-SemiBold",
    textAlign: "center",
    marginBottom: 12,
  },
  topScoreText: {
    fontSize: 16,
    color: COLORS.accent,
    textAlign: "center",
    fontFamily: "Lexend-SemiBold",
    marginTop: 4,
    marginBottom: 8,
  },
  storyWrapper: {
    flex: 1,
    marginTop: 12,
  },
  storyContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 6,
  },
  feedbackCard: {
    marginTop: 16,
    marginHorizontal: 20,
    backgroundColor: COLORS.deepBrown,
    borderRadius: 28,
    paddingVertical: 20,
    paddingHorizontal: 16,
    gap: 8,
  },
  recognized: {
    fontSize: 34,
    color: COLORS.panel,
    textAlign: "center",
    minHeight: 50,
  },
  warning: {
    fontSize: 18,
    color: COLORS.warning,
    textAlign: "center",
  },
  counter: {
    fontSize: 18,
    color: COLORS.cream,
    textAlign: "center",
  },
  congrats: {
    fontSize: 20,
    color: COLORS.success,
    textAlign: "center",
    fontFamily: "Lexend-SemiBold",
  },
  buttonContainer: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 20,
    minWidth: 140,
    alignItems: "center",
  },
  startButton: { backgroundColor: COLORS.start },
  stopButton: { backgroundColor: COLORS.stop },
  restartButton: { backgroundColor: COLORS.restart },
  ttsButton: { backgroundColor: COLORS.tts },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  dropdownButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: 10,
    borderRadius: 18,
    alignItems: "center",
    marginBottom: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "80%",
    backgroundColor: COLORS.panel,
    borderRadius: 24,
    padding: 20,
    maxHeight: "70%",
  },
  modalTitle: {
    fontSize: 22,
    color: COLORS.deepBrown,
    fontFamily: "Lexend-SemiBold",
    textAlign: "center",
    marginBottom: 12,
  },
  modalItem: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F3C99A",
  },
  modalItemText: {
    fontSize: 18,
    color: COLORS.deepBrown,
  },
  modalClose: {
    marginTop: 16,
    backgroundColor: COLORS.deepBrown,
    paddingVertical: 12,
    borderRadius: 18,
    alignItems: "center",
  },
  modalCloseText: {
    color: COLORS.panel,
    fontWeight: "700",
    fontSize: 16,
  },
});
