import { StyleSheet } from "react-native";

const COLORS = {
  background: "#FFC400",
  panel: "#FFEFD2",
  deepBrown: "#3A2B26",
  midBrown: "#4F3D39",
  accent: "#FF7A28",
  textDark: "#3A2B26",
  textLight: "#FFEFD2",
  success: "#34C759",
  warning: "#D04F4F",
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.deepBrown,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    backgroundColor: COLORS.deepBrown,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  headerTitle: {
    color: COLORS.panel,
    fontSize: 28,
    fontFamily: "Lexend-SemiBold",
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: COLORS.midBrown,
    alignItems: "center",
    justifyContent: "center",
  },
  backText: {
    color: COLORS.panel,
    fontSize: 24,
    fontWeight: "bold",
  },

  headerSubtitle: {
    color: COLORS.textLight,
    fontSize: 16,
    marginTop: 6,
    fontFamily: "OpenDyslexic-Regular",
  },
  card: {
    flex: 1,
    backgroundColor: COLORS.panel,
    marginTop: -24,
    marginHorizontal: 20,
    borderRadius: 28,
    padding: 20,
    elevation: 5,
  },
  title: {
    fontSize: 24,
    fontFamily: "Lexend-SemiBold",
    color: COLORS.textDark,
    textAlign: "center",
    marginBottom: 8,
  },
  modeSwitchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modeSwitcher: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: COLORS.accent,
  },
  modeSwitcherLabel: {
    color: COLORS.textDark,
    fontFamily: "Lexend-SemiBold",
  },
  storyWrapper: {
    flex: 1,
    marginTop: 12,
  },
  storyContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
  },
  feedbackCard: {
    marginHorizontal: 20,
    marginTop: 16,
    backgroundColor: COLORS.deepBrown,
    borderRadius: 28,
    padding: 20,
  },
  recognized: {
    fontSize: 36,
    minHeight: 48,
    color: COLORS.textLight,
    textAlign: "center",
  },
  warning: {
    fontSize: 18,
    color: COLORS.warning,
    textAlign: "center",
    marginTop: 8,
  },
  counter: {
    fontSize: 18,
    color: COLORS.textLight,
    textAlign: "center",
    marginTop: 4,
  },
  congrats: {
    fontSize: 20,
    color: COLORS.success,
    textAlign: "center",
    marginTop: 6,
  },
  buttonContainer: {
    marginTop: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 20,
    minWidth: 130,
    alignItems: "center",
  },
  startButton: { backgroundColor: "#2C872F" },
  stopButton: { backgroundColor: "#C91C1A" },
  restartButton: { backgroundColor: "#E18F15" },
  ttsButton: { backgroundColor: COLORS.accent },
  buttonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  dropdownButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: 12,
    borderRadius: 18,
    alignItems: "center",
    marginBottom: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "80%",
    maxHeight: "70%",
    backgroundColor: COLORS.panel,
    padding: 20,
    borderRadius: 24,
  },
  modalTitle: {
    fontSize: 22,
    fontFamily: "Lexend-SemiBold",
    color: COLORS.textDark,
    textAlign: "center",
    marginBottom: 12,
  },
  modalItem: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F3C99A",
  },
  modalItemText: {
    fontSize: 18,
    color: COLORS.textDark,
  },
  modalClose: {
    marginTop: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.deepBrown,
    borderRadius: 18,
    alignItems: "center",
  },
  modalCloseText: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.panel,
  },
  mathCard: {
    backgroundColor: "#FFF6E3",
    borderRadius: 24,
    padding: 16,
    marginTop: 16,
    gap: 12,
  },
  mathQuestion: {
    fontSize: 28,
    fontFamily: "Lexend-SemiBold",
    color: COLORS.textDark,
    textAlign: "center",
  },
  mathOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  mathOption: {
    flex: 1,
    backgroundColor: COLORS.accent,
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: "center",
  },
  mathOptionLabel: {
    fontSize: 20,
    fontFamily: "Lexend-Bold",
    color: COLORS.deepBrown,
  },
  mathFeedback: {
    textAlign: "center",
    fontSize: 16,
    color: COLORS.textDark,
    fontFamily: "OpenDyslexic-Regular",
  },
  mathFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  mathScore: {
    fontSize: 18,
    color: COLORS.textDark,
    fontFamily: "Lexend-SemiBold",
    textAlign: "center",
  },
  mathOptionCorrect: {
    backgroundColor: COLORS.success,
  },
  mathFeedbackCorrect: {
    color: COLORS.success,
    fontWeight: "bold",
  },
  topScoreText: {
    fontSize: 16,
    color: COLORS.accent,
    textAlign: "center",
    fontFamily: "Lexend-SemiBold",
    marginTop: 4,
  },
  mathHintCard: {
    marginHorizontal: 20,
    marginTop: 16,
    backgroundColor: "#FFF6E3",
    borderRadius: 28,
    padding: 18,
  },
  mathHintTitle: {
    fontSize: 20,
    fontFamily: "Lexend-SemiBold",
    color: COLORS.textDark,
    marginBottom: 6,
  },
  mathHintText: {
    fontSize: 16,
    color: COLORS.textDark,
    fontFamily: "OpenDyslexic-Regular",
  },
});
